//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmbraceInfinity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID_Order { get; set; }
        public string Title_Order { get; set; }
        public string Description { get; set; }
        public Nullable<int> Executor { get; set; }
        public string Customer { get; set; }
    
        public virtual Customer Customer1 { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
